language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: ce6h/G8xJSdNG3btaGCWmJNkr7BmqaU903mqF1Vyyx7AvchI9vmbo4QkA4+xYY92d4Qhf70Z0A4Ss/NW9A418gOwgMKF/VS0Gg1dnT3SobAKR0F8KN4H0mtDjU7uiUtaLK1qIKYfnbRZOTw984ofZnjJzdyTWpb+YNZbMMqHDxJRWAFJ11KiIZ1R/xcyCZs+IxpMUw1tUmi8gzk3x1x4QhCH5NLWefWsItv6/JHs3ybmqkRk9kDFRN+3czGk/61aEG7J3NQyzAT/W3YfQPwDOt5re+OX3BTsXk2br6QXU2CkTmolmARp/JFhR8QZCyqmT/+L0zOPhr0tAEiyTnq1nVKtHc3ESUHSOfiE9W4aKEfrv2tW6AiulkvA9VBCREj1V4ZoX1kArenzs4plFzyuvzYBurkntdXLwMu0nxmXqF/BNYFBY7vxtN8eA6KxEK5wc7mFyLXznf98Omqs0M6KOmqOTWDKaR8ehYd407HcjRZZF/oO7oqR2YNWX9+vg7rAr1Z0DSXozMiFcqILVMbSjbeEIhhay6mTPMxKLWx/4KjJv8FWS7OUOcRRKMqKQ5VsxP9T0PB8B4z9rR+O6OKpSwMVLyC0imVcvRYX0Qy5Krt8uiImLdIAJPajFOf7EI6Gk7PRXaxdb65ZWB0UtZwLPckUOpG54c0OG9jK/goxoBw=
  - secure: aJ6eCbj/WrIfwZpiAz968R7/My+rv4aSiYlfACJdXj8nMEgN5D9d8oALDaHs6Vk2d7hrO4Z+mLYe/A7C3HqWdvlBiwhC8b9siZH35ZV7rGqoEhg+KvizNHa0sR+xFmIaNnjTqK7nOEnbJJVTO/xOo5sFAAtG4oritJbuYjk3+WUZS/5w0F7/OrrRIF3gBVXYXJV6s3Ro3djOK2mS6OO26//nWXAadtP1091LeRBfwACrYeMNK3r9GTiuVnIo4R/KQgX7nkqiGsWsVyNGXe0dQyoQbx5lEk3o/tES1fPPBzi9LdxqOQ13/EZEiDOIzXrKO8jiwqcjgaEGZBuyihPpGQFGcDJxF0QlryWAMYH5vwSy37ZN+fCoNYQOiypXqmktMN7NVtsFa8ndfpUDnmhT8oXCMkn/jm6et5tfO9EXewBcvhBhICQfADwgDtQ9yQd3/arouQMBh8K2Ktx8FpAMz3nh0O5KGS5jDTtQ7f0XWtPhEO+uUs7SHWXkhmcXKOy//n2JHBCMmASY7bRgzDt07SluCOdpYB26mn+RBAYa2BybM25oUbDWtLUz7mIfcqcK47grljCSsTxJdBc+zgv9N67l3oAgNVu5Pwx0kp5SXSpuSY/4YzNIAx+glv+wbIgW/iThn8u1CtXjnCjRmgC+hE0louLJO4EcqkOc70YlwI4=

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn cobertura:cobertura -P !build-extras -B
cache:
  directories:
  - ~/.m2/repository
after_success:
- bash <(curl -s https://codecov.io/bash)
- bash travis-deploy-sonatype/scripts/deploy.sh 118457b0408e travis/codesigning.asc.enc travis/settings.xml
sudo: true
