language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "G3nIYMFgelgrAY8fzPhHVpdDh8lrPLLiXCBJL4yAXB0oR3aQy5JvGbP4/syT9kaBE9PfMSWNsUXeE/M91HxI2gybY8Rhjxk7fcoyFQa4oliilpCh908oUpqVW8dvQTu4XKdYMDr4V21uOmh6xEyv5O2Y+0lqHIq100Ay7ltcneSfNMB1MQHpkHy78MPr3W+FwKFELBuQ7w9RKWPmCtFZAE1ntASKNTglruJG0Iz2YSN4NrXl0J4ylIb0lZEAE2Ztdqrs5sN/xPddnPP3EX+lq6hFPQwm2ofdOUGI1haCevdn/uYzjkJL2UOS/OF9sFLCqCH77hV2B5JeblO1e+hFfynO3AI9iX9b3SR0keQJQMSLhgYXfyQLTmpbBMmlFp2pJYyYzYx+7SBD6wIaX6JeOekoLWxWivWMvpaM8e0IbIRiRQe0NnHlk+fGkOwL+Wan8prnqxOtpysBkU0lqGc3tkAuIOM00OKXGmlwejfU10wyfUzk5kW+fUY1URO2+3AodwlCF20xK9Uah0kdbQQaTJpr7PyylMKIozBzX6HEe8zSTiAPPd9ZzsEC9ad3Mpf4p0tc3uKwWwDSj9q+smx8sGYoeeECmB4FXrg7hbUIUXufvh7xegKRsBLuNtLl8FK8OajDxTDFtp2iZaAP3PC4olxYjCaTikYZ3RAUUH4+gwc="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "lBPw/Xq5R2R9crm09l6+Pswb0PmJKTwTZUwHMh2OvvKoH7nYP03zLhQO69Ud+27Zxtc6JiA7ASJa77jm9qbDAtsoIZ8f9qFlvxn93RHa9GBbMMGdN2djMYeEcU0mbhOmRDjxZXWD69JBUMOtvs4rVumPH0P9xEjceN1dGKmTqZUnWx5E3LQ76m1bUbG5eJqL1SO7GOfLFFcnFCSqKg3aiZWtiRFJK+U5oOm0k+WL0vqcTAI7D0Og6e5FiPLWTnPMZxZw3/iaSNZOV8sKLRHHvTk4WTA4q2ToRyLyJuF1yJ5TNQVgzkpl5gn7b+1lcweeQDF8UajZ0w1hnWgaurZparlrKKRWgftnDrgfhE0nobsprcuW0m//7a5Oz9uLv6JTjGqln+HlQ97AxNU75RDr/9rMeJLw5R1OfXfhU7oI1wJTNkxpgoTcpM4Fji+1mO/mKCTNjgXk62uGb/joQzca09hJcxiKoncOsY40JA6wXwy9/VImv8QcqTpDTnGoblon8IW+cOBJECqhrLESd9DeQMFg3yJ4jHo05ok1lwrQ8KX7YnaJn2BQBnPsRtJ1zSUTGYN0OaPiM1+5xcU+h9ooBrnuvxtNf2c4sTf1GUedm80o5HSDt7xLAPL7V5YWqKAA35oHdMPdSNyqKsGTahruyq43HuRqLhfAk0B5NXHxJBg="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "o7vCCsKece92CaQJV45M5aq9BNUdbnAe00SNeOJ9ifj6jS/pwlXnjsjx0RrswT6vLMq87xATZNk68QbL/f6dS/QBMOFp0bsrjE74ji5Nb9MX7lMOSfvJ6NIrBCcV3VQs5ffhKrNQbzD9WN+owgWBEiUfxdODxXgdQROdXl5svLGmigiSspYMGGoTVy46dCJ5TTR6fbbwd5RbOpFttV9pQR4fLN0PAsb7vs3NLm66HOjltPPib4gJ8RL1dQJDHi85MU7cZ2eDnaawqkiN20Z0+veKLWAvYOv/Ije2INYXj3JT4LO+aWXfyP0ZODEgA+CswxxgWxTCHjCMBcKTMpheQ+ori51y3oUBIpwP7L+LAA6stOJVpn39JuHtc82IobiqpJxDTPELgmaAMnINe36TxN5FyJEwYcj87m2qScwr8RsGHAyBXEEU3jhE7AFgxIHBcxtyWeDA5MJwIDsJaatw/lCwt9quwrBzMoWhuxIduzOyPKb8defR3GAVbyBXohvxJZiTMfy3XHteQzqq0NvrqVVn67enBIyUlZeLLdrGZBDKprXWxLJ6xSniPr7IvApOetvJBaSQXHh7VIJ+6JTXqzhbM8Uj6UqYuRlrXELpQUPdaddTSUcU/4Ol97hXIo8vAWlv3u4pu/NbE83VKzU6nr8V1Gou9hBeRSGiIoxZ3TY="
    - # ^^ GPG_KEY_NAME
    - secure: "Mo/rhHuouH67rzJZEc9Wtp0MBsWbHgxq/6zCCYiXmBOn9j6Obna/+JNd26Eq9+Y9IjjSZqY+W1WVqYWS7+JLXVi+1PmwArDacredgu8WoVU0l916hCmxAXYMsCy22oG4mtcyCeiRowqZV2rok9XfGJDULgKaCYZwT/ZU5dKbLGTHYzF/kMOJNsq/QFHqpcAL4K3+KmmKLPYgQZ+NZuClmKFtgnBCuLRcpQc6XKJh+op917rMNR4grvPvBCt8PS0Z8gGIKTEmxk4k4Yl+3SXtDm8gwNmqCtaEVr6FgJ/TZMeMTR4/RZg0YsprXJ1PSoKLL/6I/7ltT1y8WWc6lZN842wDMoxM4exLTUbKCmIfWtWy++o0G+peDSeOyB5lKKFfCJ4/JWJO57YsjYo7KZVVo4P48A0KObXqq6yc2zWwntKVhJyCbqtr7v5BqxZRlzzu26dB+f0ZbtxAUoKg2pMZAFrlUifQ5f77+ErfQPOeEvVishhWlZpW+j8oBy3EO72fvQs1GGHgCX5rzZCKPVd4Yn57by36C3nQOcMPonMp5l43+s0cSCC83WbIXhjo5OxmAWTFMH9Pt3KzQF85dCYkGLu+UhoqTsE0QMlP3H2iH25uOErfpOsvGTMj8OULecHmf+UM/5ERhaDU1bzXaNjzKr4ugZnJbdOkPiunz93jFEc="
    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - chmod +x ./cd/before-deploy.sh
  - chmod +x ./cd/deploy.sh
script: mvn test -P !build-extras -B
script: mvn cobertura:cobertura -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash travis-deploy-sonatype/scripts/deploy.sh 118457b0408e travis/codesigning.asc.enc travis/settings.xml
  - # ^^ Installs gpg2 for code signing
sudo: true
